[dev]
   command = "npm run dev"
   framework = "astro"

[build]
    command = "npm install --legacy-peer-deps && npm run build"
    publish = "dist"

[build.environment]
    NETLIFY_IMAGE_CDN_DOMAINS="a.storyblok.com"

[images]
    remote_images = ["https://a.storyblok.com/.*", "https://jee-v2.k16e.co/.*"]
