[dev]
   command = "npm run dev"
   framework = "astro"

[build]
    command = "npm cache clean --force && npm install --force && npm run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "7"
    NETLIFY_IMAGE_CDN_DOMAINS="a.storyblok.com"

[images]
    remote_images = ["https://a.storyblok.com/.*", "https://jee-v2.k16e.co/.*"]
